# SKELETON MAPS
# Type A - Based on Skeleton Type 0 - Aj, BigVegas, SportyGranny, Kaya
# Type B - Based on Skeleton Type 10
# Type C - Based on A, with finger bones retained
# Type D - 4-Fingered Skeletons, new Mixamo Data (Abe, Lola, SkeletonZombie)
# Type E - 3-Fingered Skeletons, new Mixamo Data (Doozey, Maw, Mousey)
# -------------
TYPE:
  A:
    BONES:
      - Pelvis
      - LeftUpLeg
      - LeftLeg
      - LeftFoot
      - LeftToeBase
      - RightUpLeg
      - RightLeg
      - RightFoot
      - RightToeBase
      - Hips
      - Spine
      - Spine1
      - Spine2
      - Neck
      - Head
      - LeftShoulder
      - LeftArm
      - LeftForeArm
      - LeftHand
      - RightShoulder
      - RightArm
      - RightForeArm
      - RightHand
    END_EFFECTORS:
      - LeftToeBase
      - RightToeBase
      - Head
      - LeftHand
      - RightHand
  B:
    BONES:
      - Hips
      - LeftUpLeg
      - LeftLeg
      - LeftFoot
      - LeftToeBase
      - LeftToe_End
      - RightUpLeg
      - RightLeg
      - RightFoot
      - RightToeBase
      - RightToe_End
      - Spine
      - Spine1
      - Spine1_split
      - Spine2
      - Neck
      - Head
      - HeadTop_End
      - LeftShoulder
      - LeftShoulder_split
      - LeftArm
      - LeftForeArm
      - LeftHand
      - RightShoulder
      - RightShoulder_split
      - RightArm
      - RightForeArm
      - RightHand
    END_EFFECTORS:
      - LeftToe_End
      - RightToe_End
      - HeadTop_End
      - LeftHand
      - RightHand
  C:
    BONES:
      - Pelvis
      - LeftUpLeg
      - LeftLeg
      - LeftFoot
      - LeftToeBase
      - RightUpLeg
      - RightLeg
      - RightFoot
      - RightToeBase
      - Hips
      - Spine
      - Spine1
      - Spine2
      - Neck
      - Head
      - LeftShoulder
      - LeftArm
      - LeftForeArm
      - LeftHand
      - LeftHandThumb1
      - LeftHandThumb2
      - LeftHandThumb3
      - LeftHandIndex1
      - LeftHandIndex2
      - LeftHandIndex3
      - LeftHandMiddle1
      - LeftHandMiddle2
      - LeftHandMiddle3
      - LeftHandRing1
      - LeftHandRing2
      - LeftHandRing3
      - LeftHandPinky1
      - LeftHandPinky2
      - LeftHandPinky3
      - RightShoulder
      - RightArm
      - RightForeArm
      - RightHand
      - RightHandThumb1
      - RightHandThumb2
      - RightHandThumb3
      - RightHandIndex1
      - RightHandIndex2
      - RightHandIndex3
      - RightHandMiddle1
      - RightHandMiddle2
      - RightHandMiddle3
      - RightHandRing1
      - RightHandRing2
      - RightHandRing3
      - RightHandPinky1
      - RightHandPinky2
      - RightHandPinky3
    END_EFFECTORS:
      - LeftToeBase
      - RightToeBase
      - Head
      - LeftHand
      - RightHand
  D:
    BONES:
      - Hips
      - LeftUpLeg
      - LeftLeg
      - LeftFoot
      - LeftToeBase
      - LeftToe_End
      - RightUpLeg
      - RightLeg
      - RightFoot
      - RightToeBase
      - RightToe_End
      - Spine
      - Spine1
      - Spine2
      - Neck
      - Head
      - HeadTop_End
      - LeftShoulder
      - LeftArm
      - LeftForeArm
      - LeftHand
      - LeftHandThumb1
      - LeftHandThumb2
      - LeftHandThumb3
      - LeftHandThumb4
      - LeftHandIndex1
      - LeftHandIndex2
      - LeftHandIndex3
      - LeftHandIndex4
      - LeftHandMiddle1
      - LeftHandMiddle2
      - LeftHandMiddle3
      - LeftHandMiddle4
      - LeftHandRing1
      - LeftHandRing2
      - LeftHandRing3
      - LeftHandRing4
      - LeftHandPinky1
      - LeftHandPinky2
      - LeftHandPinky3
      - LeftHandPinky4
      - RightShoulder
      - RightArm
      - RightForeArm
      - RightHand
      - RightHandThumb1
      - RightHandThumb2
      - RightHandThumb3
      - RightHandThumb4
      - RightHandIndex1
      - RightHandIndex2
      - RightHandIndex3
      - RightHandIndex4
      - RightHandMiddle1
      - RightHandMiddle2
      - RightHandMiddle3
      - RightHandMiddle4
      - RightHandRing1
      - RightHandRing2
      - RightHandRing3
      - RightHandRing4
      - RightHandPinky1
      - RightHandPinky2
      - RightHandPinky3
      - RightHandPinky4
    END_EFFECTORS:
      - LeftToe_End
      - RightToe_End
      - HeadTop_End
      - LeftHand
      - RightHand
  E:
    BONES:
      - Hips
      - LeftUpLeg
      - LeftLeg
      - LeftFoot
      - LeftToeBase
      - LeftToe_End
      - RightUpLeg
      - RightLeg
      - RightFoot
      - RightToeBase
      - RightToe_End
      - Spine
      - Spine1
      - Spine2
      - Neck
      - Head
      - HeadTop_End
      - LeftShoulder
      - LeftArm
      - LeftForeArm
      - LeftHand
      - LeftHandThumb1
      - LeftHandThumb2
      - LeftHandThumb3
      - LeftHandThumb4
      - LeftHandIndex1
      - LeftHandIndex2
      - LeftHandIndex3
      - LeftHandIndex4
      - LeftHandMiddle1
      - LeftHandMiddle2
      - LeftHandMiddle3
      - LeftHandMiddle4
      - LeftHandRing1
      - LeftHandRing2
      - LeftHandRing3
      - LeftHandRing4
      - RightShoulder
      - RightArm
      - RightForeArm
      - RightHand
      - RightHandThumb1
      - RightHandThumb2
      - RightHandThumb3
      - RightHandThumb4
      - RightHandIndex1
      - RightHandIndex2
      - RightHandIndex3
      - RightHandIndex4
      - RightHandMiddle1
      - RightHandMiddle2
      - RightHandMiddle3
      - RightHandMiddle4
      - RightHandRing1
      - RightHandRing2
      - RightHandRing3
      - RightHandRing4
    END_EFFECTORS:
      - LeftToe_End
      - RightToe_End
      - HeadTop_End
      - LeftHand
      - RightHand